# Generated by Django 3.1.7 on 2021-08-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0002_auto_20210806_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movieId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
